org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.1.2
enabled_platforms=fabric,neoforge

archives_base_name=mightyarchitect
mod_version=0.12.0
maven_group=com.timmie.mightyarchitect

architectury_version=20.0.9

fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2

neoforge_version=26.1.2.84
