modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/TimStewartJ/TheMightyArchitectury/issues"
license = "MIT"

[[mods]]
modId = "mightyarchitect"
version = "${version}"
displayName = "The Mighty Architect"
authors = "simibubi, timmie"
description = '''
Architectury port of The Mighty Architect. Design elaborate buildings within a minute!
'''
#logoFile = ""

[[dependencies.mightyarchitect]]
modId = "neoforge"
type = "required"
versionRange = "[21.8.54,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mightyarchitect]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.8,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mightyarchitect]]
modId = "architectury"
type = "required"
versionRange = "[16.0.0,)"
ordering = "AFTER"
side = "BOTH"