modLoader = "javafml"
loaderVersion = "[${meta_fml_range},)"
issueTrackerURL = "https://github.com/TimStewartJ/TheMightyArchitectury/issues"
license = "MIT"

[[mods]]
modId = "mightyarchitect"
version = "${version}"
displayName = "The Mighty Architect"
authors = "simibubi, timmie"
displayURL = "https://modrinth.com/mod/the-mighty-architectury"
logoFile = "assets/mightyarchitect/icon.png"
description = '''
Design elaborate buildings within a minute!
'''

[[mixins]]
config = "mightyarchitect.mixins.json"

[[dependencies.mightyarchitect]]
modId = "neoforge"
type = "required"
versionRange = "[${meta_neoforge_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mightyarchitect]]
modId = "minecraft"
type = "required"
versionRange = "[${meta_mc_range},${meta_mc_max})"
ordering = "NONE"
side = "BOTH"
